[paths]
# inputs
ymldb = "./yamldb"
grids = "../theory/grids/"
theory_cards = "../nufpf/assets/"
operator_card_template_name = "_template.yaml"
# outputs
operator_card_template = "./_template.yaml"
operator_cards = "../operator_cards"
ekos = "../ekos"
fktables = "../fktables"

[paths.logs]
eko = "logs/eko"
fk = "logs/fk"
