Minimizer: MINUIT
MINUIT:
  Commands: |
    set str 2

DefaultEvolution: tungsten_target

Evolutions:
  tungsten_target:
    class: LHAPDF
    set: "EPPS21nlo_CT18Anlo_W184"
    member: 0

Q0 : 1.65 #1.378404875209 # Initial scale =sqrt(1.9)

? !include constants.yaml

alphas : 0.118

byReaction:
  PineAPPL:
    muF: 1.0
    muR: 1.0
    norm: 0

#
# Profiler allows to add variations of parameters and PDF eigenvectors as additional nuisance parameters
#
Profiler:
  #Parameters:
  #  alphas: [ 0.118, 0.119, 0.117 ]  # central, up, (down) variation. If down is not given, uses symmetrizes Up variation 
  Evolutions:
    tungsten_target:
      sets:    [EPPS21nlo_CT18Anlo_W184]
      members: [[0,1,end]] # skip last replica because difference between 0 and 100 is linear combination of differences between 0 and 1-99 members
  Status: "On"               # "Off" to turn off profiler
  WriteTheo: "On"            # Can be "Off", "On" or "Asymmetric" (to store asymmetric variations)
  getChi2: "On"              # determine and report chi2 for each variation
  enableExternalProfiler: "On" # enable creation of additional files, needed for xfitter draw
  threads: 4                 # use multiprocess for calculations
  scalePdfs: 5.74456         # rescale (divide) all PDF eigenvectors by the given factor
